---
abstract: 'Parse error messages from the perl interpreter'
author:
  - 'Petar Shangov, <pshangov at yahoo.com>'
  - 'Gabor Szabo <http://szabgab.com/>'
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Differences: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-ErrorString-Perl
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::XSAccessor: 0
  File::Basename: 0
  File::Spec: 0
  Pod::Find: 0
  Pod::POM: 0.27
  perl: 5.8.7
resources:
  bugtracker: http://padre.perlide.org/trac/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Parse-ErrorString-Perl
version: 0.20
